use_frameworks!

platform :ios, '8.0'

target 'CModule_Example' do
  pod 'CModule', :path => '../'

  target 'CModule_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
